### ISSUE TITLE
Doesn't work from Korea.

### ISSUE THREAD

**Issue by Leftium** [notemapp/notemapp-web#46]
I got this error:

> Access denied
> You do not have access to notemapp.com.
> The site owner may have set restrictions that prevent you from accessing the site.

**Error details:**

    I got an error when visiting notemapp.com/.
    Error code: 1020
    Ray ID: 791b81296cb825f8
    Country: KR
    Data center: nrt08
    Timestamp: 2023-01-30 16:15:07 UTC

Confirmed it works with VPN from Seattle, USA.

**Comment by alessiovierti** [comment]
Hi, you should be good to go now.

I initially allowed traffic only from Europe and USA - I've just disabled this security rule, let me know if you still can't view it from Korea.

Thanks!
